local opt = vim.opt
opt.relativenumber = false -- Relative line numbers
vim.opt.termguicolors = true
vim.g.terminal_color_0 = "#45475A" -- Black
vim.g.terminal_color_1 = "#F38BA8" -- Red
vim.g.terminal_color_2 = "#A6E3A1" -- Green
vim.g.terminal_color_3 = "#F9E2AF" -- Yellow
vim.g.terminal_color_4 = "#89B4FA" -- Blue
vim.g.terminal_color_5 = "#F5C2E7" -- Magenta
vim.g.terminal_color_6 = "#94E2D5" -- Cyan
vim.g.terminal_color_7 = "#BAC2DE" -- White
vim.g.terminal_color_8 = "#585B70" -- Bright Black
vim.g.terminal_color_9 = "#F38BA8" -- Bright Red
vim.g.terminal_color_10 = "#A6E3A1" -- Bright Green
vim.g.terminal_color_11 = "#F9E2AF" -- Bright Yellow
vim.g.terminal_color_12 = "#89B4FA" -- Bright Blue
vim.g.terminal_color_13 = "#F5C2E7" -- Bright Magenta
vim.g.terminal_color_14 = "#94E2D5" -- Bright Cyan
vim.g.terminal_color_15 = "#A6ADC8" -- Bright White
